[general]
# Forces the hardware performance governor
desiredgov=performance

# Blocks the desktop from sleeping or locking your screen mid-game
inhibit_screensaver=1

# Disables kernel penalties for misaligned cross-cache memory calls
disable_splitlock=1

# Grants the game higher processing priority over background tasks
renice=10
ioprio=0

[cpu]
# Traps your game entirely inside the 3D V-Cache die (CCD0)
pin_cores=0,1,2,3,4,5,6,7,16,17,18,19,20,21,22,23
