# Fuzzel Configuration - Dracula Theme
font=Ubuntu:size=14
terminal=foot  # Change this to your preferred terminal
prompt="❯  "
layer=overlay

[colors]
background=282a36ff
text=f8f8f2ff
match=8be9fdff
selection=44475aff
selection-text=f8f8f2ff
selection-match=8be9fdff
border=bd93f9ff

[border]
width=2
radius=0

