# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "uas" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f4ade6f7-bd68-4ca4-8e2a-0abcd7dade82";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EC06-EFD7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

   fileSystems."/mnt/Games" =
     { device = "/dev/disk/by-uuid/e2568d95-9814-4bbc-a063-d009dd0856e9";
       fsType = "ext4";
       options = [ "defaults" "user" "exec" "nofail" ];
     };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d902dba6-f82f-4a26-a1b8-3785e34e2991"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
